name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier-jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npx prettier --check 'src/**/*.{js,jsx,json,css,md}'

      - name: Run Jest tests
        run: npm test -- --watchAll=false --passWithNoTests